[TEST]: JWT 관련 테스트 코드 작성
MyongjiWay/MyongjiWay-Server pull request #5
Opened 2024-06-30 10:01 UTC by sejineer

## 📄 Summary
> -  JwtProvider method 테스트 코드 작성
    1. accesstoken 생성 테스트
    2. refreshtoken 생성 테스트
    3. jwt signature 불일치 throw test

## 🙋🏻 More
>더 좋은 방향이 있다면 피드백 부탁드립니닷
closes #4

2024-06-30 13:13 UTC, kjb512 requested changes
다시

2024-06-30 16:33 UTC, kjb512 requested changes
고생하셨습니다.

2024-06-30 16:33 UTC, kjb512 commented on core/core-api/src/test/kotlin/com/myongjiway/core/auth/security/jwt/JwtProviderTest.kt
> +@SpringBootTest
단위 테스트로 진행하는게 좋을것같습니다.

추가로, SpringBootTest 어노테이션을 모든 테스트 위에 적는게 최선일까요? 거기서 생길 수 있는 문제점은 뭐가 있을까요?

2024-06-30 16:33 UTC, kjb512 commented on core/core-api/src/test/kotlin/com/myongjiway/core/auth/security/jwt/JwtProviderTest.kt
> +        val userId = "1234"
userId가 모든 테스트에서 중복되네요.

2024-06-30 16:33 UTC, kjb512 commented on core/core-api/src/test/kotlin/com/myongjiway/core/auth/security/jwt/JwtProviderTest.kt
> +}
Unhappy Path에 대한 테스트도 모두 고민한건가요?

2024-06-30 17:23 UTC, sejineer commented on core/core-api/src/test/kotlin/com/myongjiway/core/auth/security/jwt/JwtProviderTest.kt
> +@SpringBootTest
테스트 과정에서 서버를 여러 번 띄워야 하는 현상이 발생해 테스트 속도가 저하될 것 같습니다. 이를 위해 추후에 공통 추상클래스로 묶는 작업도 적용할 예정입니다.

2024-06-30 17:23 UTC, sejineer commented on core/core-api/src/test/kotlin/com/myongjiway/core/auth/security/jwt/JwtProviderTest.kt
> +        val userId = "1234"
userId를 다르게 하는 것이 좋을까요?

2024-06-30 17:24 UTC, sejineer commented on core/core-api/src/test/kotlin/com/myongjiway/core/auth/security/jwt/JwtProviderTest.kt
> +}
이 테스트가 Unhappy를 고려한 것이긴 합니다만 좀 더 찾아보겠읍니다,,

2024-06-30 17:37 UTC, kjb512 commented on core/core-api/src/test/kotlin/com/myongjiway/core/auth/security/jwt/JwtProviderTest.kt
> +        val userId = "1234"
묶을수 있을것 같습니다.

2024-07-04 07:56 UTC, sejineer commented
Kotest 도입 및 모든 테스트 유닛테스트로 작성하였습니다. 
- 외부 빈이 필요한 로직들은 kotest의 mockk()을 사용하여 mock 처리하고 beforeTest절에서 어떤값을 반환할지 지정하여 격리된 환경에서 unit test가 가능하도록 하였습니다.

확인 부탁드립니다!

2024-07-04 07:58 UTC, sejineer commented
![image](https://github.com/MyongjiWay/MyongjiWay-Server/assets/95167215/61ef85fa-664e-4b65-9113-2d78075d4224)
![image](https://github.com/MyongjiWay/MyongjiWay-Server/assets/95167215/c6ef9061-36eb-459a-9368-0c131b1e347a)

2024-07-07 08:08 UTC, hojinida approved these changes

2024-07-07 08:49 UTC, merged